index:
  path: /
  defaults: { _controller: 'StapsSurvey\Controller\AppController::indexAction' }

quiz:
  path: /quiz/{page}
  defaults: { _controller: 'StapsSurvey\Controller\AppController::quizAction', page: 1 }
  requirements:
    page: \d+

results:
  path: /results
  defaults: {_controller: 'StapsSurvey\Controller\AppController::resultsAction'}
