index:
  path: /
  defaults: { _controller: 'StapsSurvey\Controller\AppController::indexAction' }

survey:
  path: /survey/{page}
  defaults: { _controller: 'StapsSurvey\Controller\AppController::surveyAction', page: 1 }
  requirements:
    page: \d+